-- V1__init_schema.sql
-- Final base schema (H2 in PostgreSQL mode), without title/description.
-- GhostNet IDs start at 1001.

CREATE TABLE app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ghost_net (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,

  latitude NUMERIC(9,6) NOT NULL,
  longitude NUMERIC(9,6) NOT NULL,
  estimated_size_m2 NUMERIC(10,2),

  status VARCHAR(20) NOT NULL DEFAULT 'REPORTED',

  assigned_salvager_username VARCHAR(100),

  reported_by_username VARCHAR(100) NOT NULL DEFAULT 'anonymous',

  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),

  version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_ghost_net_status ON ghost_net(status);
